name: auto test java

on:
  push:
    branches: [ "master" ]

jobs:
  realworld_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission gradlew
        run: chmod +x gradlew
        
      - name: Build
        run: ./gradlew build -x test
        
      - name: Test
        run: ./gradlew test
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "build/test-results/test/**/*.xml"

