name: auto test java

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'temurin'
          java-version: '18'
          
      - name: Grant execute permission gradlew
        run: chmod +x gradlew
        
      - name: Build
        run: ./gradlew build -x test
      
      - name: Test
        run: SPRING_PROFILES_ACTIVE=[test] ./gradlew test
      
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml
